= LocalStorage Documentation / Documentación de LocalStorage

[role="strong"]
This document details the items stored in `localStorage` within the React application. Specifically, it focuses on the keys saved during the authentication process.

Específicamente, se centra en las claves que se guardan durante el proceso de autenticación.

* **Persistence / Persistencia :**  
  This value persists even after closing the browser window. The token should be manually removed from `localStorage` when the user logs out.
  Este valor persiste incluso después de cerrar la ventana del navegador. El token debería eliminarse manualmente del `localStorage` cuando el usuario cierre sesión.  


== LocalStorage Keys / Claves del LocalStorage 

=== `token`
* ** Description / Descripción:**  
  This key stores the authentication token received from the server after a successful login.
  Esta clave almacena el token de autenticación recibido del servidor después de un inicio de sesión exitoso.  


* ** Data Type / Tipo de Dato:**  
  `string`

* **Usage / Uso :**  
  The `token` is used to authenticate future requests to the API. Storing the token in `localStorage` allows the application to keep the user authenticated between page reloads.
  El `token` se utiliza para autenticar futuras solicitudes a la API. Almacenar el token en el `localStorage` permite que la aplicación mantenga al usuario autenticado entre recargas de página.  
 
* **Example Value / Ejemplo de Valor :**  
  `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c`

=== `username`
* **Description / Descripción :**  
  This key stores the username of the user who has logged in.
  Esta clave almacena el nombre de usuario del usuario que ha iniciado sesión.  

* **Data Type / Tipo de Dato :**  
  `string`

* **Usage / Uso :**  
  The `username` is stored to display the username in the user interface.
  El `username` se almacena para mostrar el nombre de usuario en la interfaz de usuario.  
  
* **Example Value / Ejemplo de Valor :**  
  `john_doe`
